/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Volunteer;
import BusinessModel.Employee.Employee;
import BusinessModel.Organization.Organization;
import BusinessModel.Organization.OrganizationDirectory;
import BusinessModel.Organization.VolunteerOrganization;
//import com.sun.glass.events.KeyEvent;
import java.awt.event.KeyEvent;
import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import UserInterface.Profile.ComputerVision;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author akhileshdongre
 */
public class ManageEmployee extends javax.swing.JPanel {
     private OrganizationDirectory organizationDirectory;
     private JPanel downJPanel;
     String selectedImagePath;
     
    /**
     * Creates new form ManageEmployee
     */
    public ManageEmployee(JPanel downJPanel, OrganizationDirectory organizationDirectory) {
        initComponents();
        this.downJPanel = downJPanel;
        this.organizationDirectory = organizationDirectory; 
        populateOrganizationComboBox();
        populateOrganizationEmpComboBox();
        
    }
    
    public void populateOrganizationComboBox(){
        orgComboBox.removeAllItems();
        
        for (Organization organization : organizationDirectory.getOrganizationList()){
            if(organization instanceof VolunteerOrganization)
            orgComboBox.addItem(organization);
        }
    }
    
    public void populateOrganizationEmpComboBox(){
        orgselectComboBox.removeAllItems();
        
        for (Organization organization : organizationDirectory.getOrganizationList()){
            if(organization instanceof VolunteerOrganization)
            orgselectComboBox.addItem(organization);
        }
    }

    private void populateTable(Organization organization){
        DefaultTableModel model = (DefaultTableModel) empTbl.getModel();
        
        model.setRowCount(0);
        
        for (Employee employee : organization.getEmployeeDirectory().getEmployeeList()){
            Object[] row = new Object[3];
            row[2] = employee.getId();
            row[0] = employee.getEmpname();
            row[1] = organization.getOrganizationName();
            model.addRow(row);
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        orgselectComboBox = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        nameTxt = new javax.swing.JTextField();
        addBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        empTbl = new javax.swing.JTable();
        orgComboBox = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ProfileTxtField = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        uploadBtn = new javax.swing.JButton();
        captureBtn = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(66, 160, 236));

        jLabel1.setBackground(new java.awt.Color(66, 160, 236));
        jLabel1.setFont(new java.awt.Font("Malayalam MN", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Manage Employee");

        backBtn.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        backBtn.setText("BACK");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(252, 252, 252)
                .addComponent(jLabel1)
                .addContainerGap(423, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(backBtn))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        jLabel3.setText("Organization: ");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 112, -1, -1));

        orgselectComboBox.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        add(orgselectComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 109, 251, -1));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        jLabel4.setText("Name          :");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 145, 92, -1));

        nameTxt.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        nameTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nameTxtKeyTyped(evt);
            }
        });
        add(nameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 145, 251, -1));

        addBtn.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        addBtn.setText("Add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        add(addBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 460, 251, -1));

        empTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Type", "ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(empTbl);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(466, 109, 516, 654));

        orgComboBox.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        orgComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orgComboBoxActionPerformed(evt);
            }
        });
        add(orgComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(731, 79, 251, -1));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        jLabel2.setText("Organization: ");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(634, 82, -1, -1));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        jLabel5.setText("Profile Photo          :");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 130, -1));

        ProfileTxtField.setBackground(new java.awt.Color(102, 102, 102));
        add(ProfileTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 150, 130));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        jLabel7.setText("Sex          :");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 90, -1));

        uploadBtn.setText("Upload");
        uploadBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadBtnActionPerformed(evt);
            }
        });
        add(uploadBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 420, 100, 20));

        captureBtn.setText("Capture");
        captureBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                captureBtnActionPerformed(evt);
            }
        });
        add(captureBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 420, 110, 20));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 240, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        downJPanel.remove(this);
        CardLayout layout = (CardLayout) downJPanel.getLayout();
        layout.previous(downJPanel);
    }//GEN-LAST:event_backBtnActionPerformed

    private void nameTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameTxtKeyTyped
        char c= evt.getKeyChar();
        if(!(Character.isAlphabetic(c)) || (c==KeyEvent.VK_DELETE) || (c==KeyEvent.VK_BACK_SPACE))
        {
            evt.consume();
        }
    }//GEN-LAST:event_nameTxtKeyTyped

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        if(nameTxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Name text field can't be empty");
        }
        else{

            Organization organization =(Organization) orgselectComboBox.getSelectedItem();
            String name = nameTxt.getText();

            organization.getEmployeeDirectory().createEmployee(name);

            populateTable(organization);
            nameTxt.setText(" ");
        }
    }//GEN-LAST:event_addBtnActionPerformed

    private void orgComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orgComboBoxActionPerformed
        Organization organization = (Organization)orgComboBox.getSelectedItem();

        if (organization != null){
            populateTable(organization);

        }
    }//GEN-LAST:event_orgComboBoxActionPerformed

    private void uploadBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadBtnActionPerformed
        JFileChooser browseImageFile = new JFileChooser();
        FileNameExtensionFilter fnef = new FileNameExtensionFilter("IMAGES","png","jpg","jpeg");
        browseImageFile.addChoosableFileFilter(fnef);
        int ShowOpenDialogue = browseImageFile.showOpenDialog(null);
        File selectedImageFile = browseImageFile.getSelectedFile();
        selectedImagePath = selectedImageFile.getAbsolutePath();
        //lblImageIcon.setVisible(true);
        //Display image on jLablel1
        ImageIcon ii = new ImageIcon(selectedImagePath);
        //Resize image
        Image image = ii.getImage().getScaledInstance(100,100, Image.SCALE_SMOOTH);
        ProfileTxtField.setIcon(new ImageIcon(image));
        ProfileTxtField.setVisible(true);
        uploadBtn.setText("Change Image");
    }//GEN-LAST:event_uploadBtnActionPerformed

    private void captureBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_captureBtnActionPerformed
        ComputerVision jf2 = new ComputerVision();
        jf2.show();
        jf2.setDefaultCloseOperation(jf2.DISPOSE_ON_CLOSE);

    }//GEN-LAST:event_captureBtnActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ProfileTxtField;
    private javax.swing.JButton addBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton captureBtn;
    private javax.swing.JTable empTbl;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JComboBox orgComboBox;
    private javax.swing.JComboBox orgselectComboBox;
    private javax.swing.JButton uploadBtn;
    // End of variables declaration//GEN-END:variables
}

