/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Volunteer;
import BusinessModel.EcoSystem;
import BusinessModel.Enterprise.Enterprise;
import java.awt.CardLayout;
import javax.swing.JPanel;
/**
 *
 * @author akhileshdongre
 */
public class VolunteerAdminWorkArea extends javax.swing.JPanel {
    private JPanel downJPanel;
    private Enterprise enterprise;
    
    /**
     * Creates new form VolunteerAdminWorkArea
     */
    public VolunteerAdminWorkArea(JPanel downJPanel,Enterprise enterprise) {
        initComponents();
        this.enterprise=enterprise;
        this.downJPanel=downJPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        manageEmployeeJBtn = new javax.swing.JButton();
        manageUserAccountJBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(66, 160, 236));

        jLabel1.setFont(new java.awt.Font("Malayalam MN", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Volunteer Organization ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(356, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(366, 366, 366))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        manageEmployeeJBtn.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        manageEmployeeJBtn.setText("MANAGE EMPLOYEE");
        manageEmployeeJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageEmployeeJBtnActionPerformed(evt);
            }
        });
        add(manageEmployeeJBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 204, 258, 70));

        manageUserAccountJBtn.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        manageUserAccountJBtn.setText("MANAGE USER ACCOUNT");
        manageUserAccountJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageUserAccountJBtnActionPerformed(evt);
            }
        });
        add(manageUserAccountJBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 292, 258, 71));
    }// </editor-fold>//GEN-END:initComponents

    private void manageEmployeeJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageEmployeeJBtnActionPerformed
        ManageEmployee mng = new ManageEmployee(downJPanel, enterprise.getOrganizationDirectory());
        downJPanel.add("ManageEmployee", mng);
        CardLayout layout = (CardLayout) downJPanel.getLayout();
        layout.next(downJPanel);
    }//GEN-LAST:event_manageEmployeeJBtnActionPerformed

    private void manageUserAccountJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageUserAccountJBtnActionPerformed
        ManageUserAccount mng = new ManageUserAccount(downJPanel, enterprise);
        downJPanel.add("ManageUserAccount", mng);
        CardLayout layout = (CardLayout) downJPanel.getLayout();
        layout.next(downJPanel);
    }//GEN-LAST:event_manageUserAccountJBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton manageEmployeeJBtn;
    private javax.swing.JButton manageUserAccountJBtn;
    // End of variables declaration//GEN-END:variables
}

