/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.NGOManager;
import BusinessModel.EcoSystem;
import BusinessModel.Enterprise.Enterprise;
import BusinessModel.Organization.Organization;
import BusinessModel.UserAccount.UserAccount;
import BusinessModel.WorkQueue.HelpSeekerWorkReq;
import BusinessModel.WorkQueue.NGOWorkReq;
import BusinessModel.WorkQueue.NGOSupplyWorkReq;
import BusinessModel.WorkQueue.WorkReq;
//import com.sun.glass.events.KeyEvent;
import java.awt.event.KeyEvent;
import java.awt.CardLayout;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
/**
 *
 * @author adhar
 */
public class ManagerWorkArea extends javax.swing.JPanel {
    private JPanel downJPanel;
    private UserAccount UserAccount;
    private Organization org;
    private Enterprise enterprise;
    private EcoSystem ESystem;
    private Date d;
    private SimpleDateFormat s;
    /**
     * Creates new form ManagerWorkArea
     */
    public ManagerWorkArea(JPanel downJPanel, UserAccount UserAccount, Organization org, Enterprise enterprise, EcoSystem ESystem) {
        initComponents();
        this.downJPanel=downJPanel;
        this.UserAccount=UserAccount;
        this.org=org;
        this.enterprise=enterprise;
        this.ESystem=ESystem;
        completeBtn.setEnabled(false);
        d = new Date();
        s = new SimpleDateFormat("MM/dd/YY");
        populateEventTable();
        populateWorkQueueTable();
    }
    
    public void populateEventTable()
    {
         DefaultTableModel model = (DefaultTableModel) ngoeventTbl.getModel();
        
        model.setRowCount(0);
        
        
        for (WorkReq work : org.getWorkQueue().getWorkRequestList()){
           if(work instanceof NGOWorkReq){ 
            Object[] row = new Object[10];
            row[0] = ((NGOWorkReq) work).getTitle();
            row[1] = ((NGOWorkReq) work).getDescription();
            row[2] =  work.getDateOfRequest();
            row[3] = ((NGOWorkReq) work).getLocation();
            row[4] = ((NGOWorkReq) work).getVolunteerRequired();
            row[5] = ((NGOWorkReq) work).getVolunteerAcquired();
           // row[6] = work;
            
            model.addRow(row);
           }
        }
    }
    
    public void populateWorkQueueTable(){
         DefaultTableModel model = (DefaultTableModel) requestJTable.getModel();
        
        model.setRowCount(0);
        
        
        for (WorkReq work : ESystem.getWorkQueue().getWorkRequestList()){
           if(work instanceof HelpSeekerWorkReq){
               if((work.getStatus().equalsIgnoreCase("Assigned To NGO"))||(work.getStatus().equalsIgnoreCase("NGO ASSIGNED the Request"))){
                   
               
            Object[] row = new Object[10];
            row[0] = work.getSender().getEmployee().getEmpname();
            row[1] = work.getSubject();
            row[2] = ((HelpSeekerWorkReq) work).getDescription();
            row[3] = ((HelpSeekerWorkReq) work).getLocation();
            row[4] = work.getDateOfRequest();
            row[5] = work;
            row[6] = work.getReciever();
            
            model.addRow(row);
           }
        }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ngoeventTbl = new javax.swing.JTable();
        requestBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        vRequiredTxt = new javax.swing.JTextField();
        dateChooser = new com.toedter.calendar.JDateChooser();
        createBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        locationTxt = new javax.swing.JTextField();
        titleTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        descTxt = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        completeBtn = new javax.swing.JButton();
        AssignTomeBtn = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        requestJTable = new javax.swing.JTable();
        volunteerBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(66, 160, 236));

        jLabel1.setFont(new java.awt.Font("Malayalam MN", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("NGO Manager Work Area");

        backBtn.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        backBtn.setText("BACK");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(278, 278, 278)
                .addComponent(jLabel1)
                .addContainerGap(393, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        ngoeventTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Event Title", "Description", "Date", "Location", "Volunteers Required", "Volunteers acquired"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(ngoeventTbl);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 127, 1035, 133));

        requestBtn.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        requestBtn.setText("Request for supplies");
        requestBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestBtnActionPerformed(evt);
            }
        });
        add(requestBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(887, 84, -1, 36));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        jLabel7.setText("Volunteers Required: ");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 338, -1, -1));
        add(vRequiredTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(658, 335, 217, 25));
        add(dateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(658, 305, 217, -1));

        createBtn.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        createBtn.setText("Create Event");
        createBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBtnActionPerformed(evt);
            }
        });
        add(createBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 305, -1, 41));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        jLabel6.setText("Date:     ");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 305, -1, -1));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        jLabel4.setText("Location: ");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(574, 369, 72, -1));
        add(locationTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(658, 367, 217, -1));
        add(titleTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 305, 168, -1));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        jLabel3.setText("Event Title: ");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 307, 78, -1));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        jLabel8.setText("CREATE EVENT: ");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 278, -1, -1));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        jLabel5.setText("Description: ");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 334, -1, -1));

        descTxt.setColumns(20);
        descTxt.setRows(5);
        jScrollPane3.setViewportView(descTxt);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 334, -1, 66));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        jLabel9.setText("PENDING REQUESTS:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(359, 413, -1, -1));

        completeBtn.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        completeBtn.setText("Complete");
        completeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                completeBtnActionPerformed(evt);
            }
        });
        add(completeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(892, 544, 155, 38));

        AssignTomeBtn.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        AssignTomeBtn.setText("Assign to Me");
        AssignTomeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AssignTomeBtnActionPerformed(evt);
            }
        });
        add(AssignTomeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 544, 160, 38));

        requestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Subject", "Description", "Location", "Date", "Status", "Help Provider"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(requestJTable);

        add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 446, 1035, 91));

        volunteerBtn.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        volunteerBtn.setText(" Volunteer Analysis");
        volunteerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volunteerBtnActionPerformed(evt);
            }
        });
        add(volunteerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(716, 84, 159, 36));
    }// </editor-fold>//GEN-END:initComponents
    
    
    
    private void requestBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestBtnActionPerformed
        SupplyRequest sr = new SupplyRequest(downJPanel,UserAccount,org, enterprise,ESystem);
        downJPanel.add("ManageEmployee", sr);
        CardLayout layout = (CardLayout) downJPanel.getLayout();
        layout.next(downJPanel);
    }//GEN-LAST:event_requestBtnActionPerformed

    private void createBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBtnActionPerformed
        try{
            if(titleTxt.getText().isEmpty() || descTxt.getText().isEmpty() || locationTxt.getText().isEmpty() || vRequiredTxt.getText().isEmpty()){
                JOptionPane.showMessageDialog(null,"Text Field(s) can't be empty");
            }else{

                String event = titleTxt.getText();
                String desp = descTxt.getText();
                String location = locationTxt.getText();
                Date date = dateChooser.getDate();
                int req = Integer.parseInt(vRequiredTxt.getText());

                if(event.equals("") || event.isEmpty() && desp.equals("") || desp.isEmpty() && location.equals("")|| location.isEmpty())
                {
                    JOptionPane.showMessageDialog(null, "Please enter valid request");
                    return;
                }

                NGOWorkReq request = new NGOWorkReq();
                request.setTitle(event);
                request.setDescription(desp);
                request.setLocation(location);
                request.setVolunteerRequired(req);
                request.setStatus("Not Joined");
                //  request.setvAcquired(req);
                request.setDateOfRequest(date);

                //request.setStatus("Requested");request.setSender(account);
                org.getWorkQueue().getWorkRequestList().add(request);
                UserAccount.getWorkQueue().getWorkRequestList().add(request);
                ESystem.getWorkQueue().getWorkRequestList().add(request);
                populateEventTable();

                titleTxt.setText("");
                vRequiredTxt.setText("");
                descTxt.setText("");
                locationTxt.setText("");
                dateChooser.setCalendar(null);
            }
        }catch(NumberFormatException e){}

    }//GEN-LAST:event_createBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed

    }//GEN-LAST:event_backBtnActionPerformed

    private void completeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_completeBtnActionPerformed
        int selectedRow = requestJTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select the row to assign the account", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {

            HelpSeekerWorkReq p = (HelpSeekerWorkReq) requestJTable.getValueAt(selectedRow, 5);

            /* if (p.getReciever() != null) {
                if (p.getStatus().equals("Pending")) {
                    UserAccount a = p.getSender();
                    if (s.getVaccineList().getVaccineList().size() <= 0) {
                        JOptionPane.showMessageDialog(null, "No Stock available. Request from Supplier");
                        return;
                    }
                    for (Vaccine v : s.getVaccineList().getVaccineList()) {
                        if (p.getVaccine().getVaccineName().equals(v.getVaccineName())) {
                            if (v.getQuantity() - p.getQuantity() < 0) {
                                JOptionPane.showMessageDialog(null, "No enough Vaccines for supply. Wait for sometime");
                                return;
                            }
                            v.setQuantity(v.getQuantity() - p.getQuantity());
                        } else {
                            JOptionPane.showMessageDialog(null, "No Stock available. Request from Supplier.");
                        }
                    }*/
                    p.setStatus("Complete");
                    p.setReciever(UserAccount);
                    JOptionPane.showMessageDialog(null, "You have successfully completed the request");
                    populateWorkQueueTable();
                    completeBtn.setEnabled(false);
                    /*populateAvailable();
                } else {
                    JOptionPane.showMessageDialog(null, "You cannot complete it two times.");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Please assign first");
            }

            */
        }   // TODO add your handling code here:
    }//GEN-LAST:event_completeBtnActionPerformed

    private void AssignTomeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AssignTomeBtnActionPerformed
        int selectedRow = requestJTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select the row to assign the account", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {

            HelpSeekerWorkReq hswr = (HelpSeekerWorkReq) requestJTable.getValueAt(selectedRow, 5);

            hswr.setStatus("NGO ASSIGNED the Request");
            hswr.setReciever(UserAccount);

            populateWorkQueueTable();
            completeBtn.setEnabled(true);

        }
    }//GEN-LAST:event_AssignTomeBtnActionPerformed

    private void volunteerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volunteerBtnActionPerformed
        /*        VolunteerList vl= new VolunteerList(userProcessContainer,account,organization, enterprise,system);
        userProcessContainer.add("VolunteerList", vl);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);*/
        DefaultCategoryDataset d = new DefaultCategoryDataset();

        for (WorkReq work : org.getWorkQueue().getWorkRequestList()){
            if(work instanceof NGOWorkReq)
            {

                d.setValue(((NGOWorkReq) work).getVolunteerAcquired(),"Event List",((NGOWorkReq) work).getTitle());

            }
        }

        JFreeChart chart = ChartFactory.createBarChart("Volunteers Acquired", "Event Name", "Volunteers Participated", d, PlotOrientation.VERTICAL, false, true, false);
        CategoryPlot p = chart.getCategoryPlot();
        p.setRangeGridlinePaint(Color.blue);
        ChartFrame f = new ChartFrame("Volunteer Analysis",chart);
        f.setVisible(true);
        f.setSize(500,400);
    }//GEN-LAST:event_volunteerBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AssignTomeBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton completeBtn;
    private javax.swing.JButton createBtn;
    private com.toedter.calendar.JDateChooser dateChooser;
    private javax.swing.JTextArea descTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField locationTxt;
    private javax.swing.JTable ngoeventTbl;
    private javax.swing.JButton requestBtn;
    private javax.swing.JTable requestJTable;
    private javax.swing.JTextField titleTxt;
    private javax.swing.JTextField vRequiredTxt;
    private javax.swing.JButton volunteerBtn;
    // End of variables declaration//GEN-END:variables
}

